plugins {
    id 'java-library'
    id 'maven-publish'
    id 'com.gradleup.shadow'
    id 'xyz.jpenilla.run-paper' version '3.0.2'
}

base {
    archivesName = "$rootProject.archives_name-$project.name"
}

configurations {
    core {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom core
    runtimeClasspath.extendsFrom core
    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}

repositories {
    mavenCentral()
    maven { url 'https://jitpack.io' }
    maven {
        name = 'PaperMC'
        url = 'https://repo.papermc.io/repository/maven-public/'
    }
}

dependencies {
    compileOnly "io.papermc.paper:paper-api:${rootProject.minecraft_version}-R0.1-SNAPSHOT"

    core(project(path: ':core'))
    shadowBundle(project(path: ':core')) { transitive = false }

    compileOnly "org.projectlombok:lombok:$rootProject.lombok_version"
    annotationProcessor "org.projectlombok:lombok:$rootProject.lombok_version"
    testCompileOnly "org.projectlombok:lombok:$rootProject.lombok_version"
    testAnnotationProcessor "org.projectlombok:lombok:$rootProject.lombok_version"
    testImplementation "org.junit.jupiter:junit-jupiter:$rootProject.junit_version"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher"
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

tasks.withType(JavaCompile).configureEach {
    options.release = 21
    options.encoding = 'UTF-8'
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}

tasks.processResources {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    inputs.property('version', project.version)
    inputs.property('apiVersion', rootProject.minecraft_version)
    filesMatching('paper-plugin.yml') {
        expand(
                version: project.version,
                apiVersion: rootProject.minecraft_api_version
        )
    }
    filesMatching('plugin.yml') {
        expand(
                version: project.version,
                apiVersion: rootProject.minecraft_api_version
        )
    }
}

tasks.shadowJar {
    configurations = [project.configurations.shadowBundle]
    archiveClassifier = ''
}

tasks.assemble {
    dependsOn tasks.shadowJar
}

tasks.runServer {
    minecraftVersion("${rootProject.minecraft_version}")
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId = base.archivesName.get()
            from components.java
        }
    }
}
